# Generated by Django 4.1.4 on 2023-01-05 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventssub',
            new_name='Events',
        ),
    ]
