# Generated by Django 4.1.4 on 2023-01-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_eventssub_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=251, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('time_duration', models.CharField(blank=True, max_length=10, null=True)),
                ('location_link', models.TextField(blank=True, null=True)),
                ('venue', models.TextField(blank=True, null=True)),
                ('event_day', models.CharField(choices=[('Day1', 'Day1'), ('Day2', 'Day2'), ('Both', 'Both')], max_length=9)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
