# Generated by Django 4.1.4 on 2023-01-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_highlightevents_events_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='events',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
