# Generated by Django 4.1.4 on 2023-01-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_events_icon_events_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=251, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
