# Generated by Django 4.1.4 on 2023-01-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.CharField(blank=True, choices=[('Live', 'Live'), ('Upcoming', 'Upcoming'), ('Dead', 'Dead')], max_length=9, null=True),
        ),
    ]
