# Generated by Django 4.1.4 on 2023-01-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_events_description_events_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='end_hour',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='end_minute',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start_hour',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start_minute',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
