# Generated by Django 4.1.4 on 2023-01-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_generalfaqs_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='type_event',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Startup', 'Startup'), ('Professional', 'Professional'), ('Incubator', 'Incubator'), ('Investor', 'Investor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.CharField(blank=True, choices=[('Lecture Hall Complex', 'Lecture Hall Complex'), ('SAC', 'SAC'), ('OAT', 'OAT'), ('SAC Backlawns', 'SAC Backlawns'), ('Convocation Hall', 'Convocation Hall'), ('Physics Parking Lot', 'Physics Parking Lot'), ('SAC Parking Lot', 'SAC Parking Lot')], max_length=30, null=True),
        ),
    ]
